using Microsoft.EntityFrameworkCore;
using RestaurantBilling.Data;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;
using System.IdentityModel.Tokens.Jwt;
using RestaurantBilling.Middleware;

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// Add services
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddScoped<RestaurantBilling.Services.IEmailService, RestaurantBilling.Services.EmailService>();
builder.Services.AddScoped<RestaurantBilling.Services.IReportService, RestaurantBilling.Services.ReportService>();
builder.Services.AddScoped<RestaurantBilling.Services.IExpenseService, RestaurantBilling.Services.ExpenseService>();
builder.Services.AddHostedService<RestaurantBilling.Services.ReportGenerationService>();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Restaurant Billing API", Version = "v1" });
    
    // Configure Swagger to use JWT
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            new string[] {}
        }
    });
});

// Configure JWT Authentication
var jwtKey = builder.Configuration["Jwt:Key"];
var jwtIssuer = builder.Configuration["Jwt:Issuer"];
var jwtAudience = builder.Configuration["Jwt:Audience"];

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtIssuer,
            ValidAudience = jwtAudience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey ?? "DefaultSecretKey_PleaseChange_At_Least_32_Chars"))
        };
    });

// Configure CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

// Configure Entity Framework
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(connectionString));

// Fix claim mapping to avoid NameIdentifier transformation issues
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

var app = builder.Build();
// app.UseDefaultFiles(); // Frontend is now separate
// app.UseStaticFiles(); 

app.UseRouting();
// Global exception handling
app.UseMiddleware<ExceptionHandlingMiddleware>();

// Configure HTTP pipeline
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

// app.UseHttpsRedirection(); // Commented out for easier local frontend development
app.UseCors("AllowFrontend");
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

// Ensure database and tables are created automatically
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    try
    {
        // This will create the database and all tables automatically if they don't exist
        // This will create the database and all tables automatically if they don't exist
        db.Database.EnsureCreated();

        // MANUALLY CREATE INCORRECTLY MISSING TABLES (Fix for existing DBs)
        try 
        {
            db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""ExpenseCategories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_ExpenseCategories"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ExpenseCategories_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
                
                CREATE INDEX IF NOT EXISTS ""IX_ExpenseCategories_UserId"" ON ""ExpenseCategories"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExpenseCategories_IsActive"" ON ""ExpenseCategories"" (""IsActive"");

                CREATE TABLE IF NOT EXISTS ""Expenses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Date"" timestamp with time zone NOT NULL,
                    ""Amount"" numeric(18,2) NOT NULL,
                    ""CategoryId"" integer NOT NULL,
                    ""PaymentMethod"" character varying(50) NOT NULL,
                    ""Description"" character varying(500),
                    ""VendorName"" character varying(100),
                    ""ReceiptImagePath"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_Expenses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Expenses_ExpenseCategories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""ExpenseCategories"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Expenses_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS ""IX_Expenses_CategoryId"" ON ""Expenses"" (""CategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_Expenses_Date"" ON ""Expenses"" (""Date"");
                CREATE INDEX IF NOT EXISTS ""IX_Expenses_PaymentMethod"" ON ""Expenses"" (""PaymentMethod"");
                CREATE INDEX IF NOT EXISTS ""IX_Expenses_UserId"" ON ""Expenses"" (""UserId"");

                -- Update Bills table with Customer details
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Bills' AND column_name='CustomerName') THEN
                        ALTER TABLE ""Bills"" ADD COLUMN ""CustomerName"" character varying(100);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Bills' AND column_name='CustomerPhone') THEN
                        ALTER TABLE ""Bills"" ADD COLUMN ""CustomerPhone"" character varying(20);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Products' AND column_name='IsFavorite') THEN
                        ALTER TABLE ""Products"" ADD COLUMN ""IsFavorite"" boolean DEFAULT false;
                    END IF;

                    CREATE TABLE IF NOT EXISTS ""ProductCategories"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Name"" character varying(100) NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UserId"" integer NOT NULL,
                        CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_ProductCategories_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                    );
                    
                    CREATE INDEX IF NOT EXISTS ""IX_ProductCategories_UserId"" ON ""ProductCategories"" (""UserId"");
                    CREATE INDEX IF NOT EXISTS ""IX_ProductCategories_IsActive"" ON ""ProductCategories"" (""IsActive"");
                END $$;
            ");
        }
        catch (Exception ex)
        {
             // Log but don't stop if tables already exist or other issue
             var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
             logger.LogWarning(ex, "Attempted to create expense tables provided feedback.");
        }

        // Seed default report settings
        if (!db.ReportSchedules.Any())
        {
            db.ReportSchedules.AddRange(new List<RestaurantBilling.Models.ReportSchedule>
            {
                new() { ReportType = "Daily", ScheduledTime = new TimeSpan(0, 0, 0), IsActive = true },
                new() { ReportType = "Weekly", ScheduledTime = new TimeSpan(0, 0, 0), DayOfWeek = DayOfWeek.Monday, IsActive = true },
                new() { ReportType = "Monthly", ScheduledTime = new TimeSpan(0, 0, 0), DayOfMonth = 1, IsActive = true }
            });
        }
        if (!db.GlobalSettings.Any(s => s.Key == "report_emails"))
        {
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "report_emails", Value = "admin@restaurant.com" });
        }
        
        // Seed Tax Settings
        if (!db.GlobalSettings.Any(s => s.Key == "gst_enabled"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "gst_enabled", Value = "true" });
        if (!db.GlobalSettings.Any(s => s.Key == "gst_percentage"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "gst_percentage", Value = "5" });
        if (!db.GlobalSettings.Any(s => s.Key == "service_charge_enabled"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "service_charge_enabled", Value = "true" });
        if (!db.GlobalSettings.Any(s => s.Key == "service_charge_percentage"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "service_charge_percentage", Value = "5" });

        // Seed default restaurant header settings
        if (!db.GlobalSettings.Any(s => s.Key == "restaurant_name"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "restaurant_name", Value = "My Restaurant" });
        if (!db.GlobalSettings.Any(s => s.Key == "restaurant_address"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "restaurant_address", Value = "123, Main Street" });
        if (!db.GlobalSettings.Any(s => s.Key == "restaurant_phone"))
            db.GlobalSettings.Add(new RestaurantBilling.Models.GlobalSetting { Key = "restaurant_phone", Value = "+91-00000 00000" });

        db.SaveChanges();
    }
    catch (Exception ex)
    {
        // Log error if database creation fails
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "An error occurred while creating the database.");
    }
}

app.Run();
